# Habilita o console de saída via UART (usado por PRINTK e LOG)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Suporte ao Printk para exibição de mensagens de depuração
CONFIG_PRINTK=y

# (Opcional) Sistema de Logs do Zephyr com formatação de cores e níveis
CONFIG_LOG=y

# (Opcional) Suporte a GPIO, ativado caso utilize pinos de entrada/saída (e.g. LEDs, botões)
CONFIG_GPIO=y

CONFIG_PWM=y